# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpath', models.CharField(max_length=128)),
                ('action_type', models.CharField(max_length=16)),
                ('wait_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=1024)),
                ('repeat_time', models.IntegerField(default=1)),
                ('check_wait_time', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TestPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=512)),
                ('browsers', models.CharField(max_length=128)),
                ('browser_high_width', models.CharField(max_length=128)),
                ('browser_window_position', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='test_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TestPost'),
        ),
        migrations.AddField(
            model_name='action',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Case'),
        ),
    ]
