# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpath', models.CharField(max_length=128)),
                ('action_type', models.CharField(max_length=16)),
                ('input', models.CharField(max_length=1024)),
                ('wait_time', models.IntegerField(default=0)),
                ('ext', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=1024)),
                ('repeat_time', models.IntegerField(default=1)),
                ('check_wait_time', models.IntegerField(default=1)),
                ('browsers', models.CharField(max_length=128)),
                ('browser_window_size', models.CharField(max_length=128)),
                ('browser_window_position', models.CharField(max_length=128)),
                ('browser_scroll_position', models.CharField(max_length=128)),
                ('ext', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(max_length=12)),
                ('check_data', models.CharField(max_length=1024)),
                ('check_result', models.IntegerField(default=0)),
                ('ext', models.TextField(max_length=1024)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('case_name', models.CharField(max_length=64)),
                ('browser', models.CharField(max_length=32)),
                ('resolution', models.CharField(max_length=32)),
                ('browser_size', models.CharField(max_length=32)),
                ('result', models.IntegerField()),
                ('result_content', models.TextField(max_length=1024)),
                ('ext', models.TextField(max_length=1024)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Case')),
            ],
        ),
        migrations.CreateModel(
            name='TestPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('ext', models.TextField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='test_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TestPost'),
        ),
        migrations.AddField(
            model_name='action',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Case'),
        ),
    ]
